### ISSUE TITLE
MacOS Release - x86_64/arm64

### ISSUE THREAD

**Issue by felipemeamaral** [GhostlyDark/EMG#6]
Hello, @GhostlyDark!
Firstly, id lime to thank you for this amazing project and your efforts to improve on such a gray area like mupen64 GUI.
But, since you're using Electron as a front-end, I'd like to know if it's on your plans a macOS release. 
The GUI part should not be complicated, but I guess it has complications to build mupen64 and its plugin for the Apple ecosystem. 
Once again, thank for such a great project!

**Comment by GhostlyDark** [comment]
The issue really isn't the front-end, but indeed building mupen64plus and especially building some its plugins (like Parallel RDP) and overall testing it on macOS. Targeting arm64 instead of x86_64 adds to the challenge. I do not own any Apple devices and doing the testing in Virtual Machines isn't exactly feasible. If somebody was to regurlarly test and build it for that platform, I'd support it. But I can't be bothered to support that ecosystem by my own.

**Comment by GhostlyDark** [comment]
Building should work now. I have yet to figure out how to reliably bundle dependencies before release files can be a thing and possibly some other quirks I missed. Right now it's x86_64 only, as I don't have access to any arm64 devices.
